### ISSUE TITLE
Can't import changes in the core store table

### ISSUE THREAD

**Issue by jklimonda** [boazpoolman/strapi-plugin-config-sync#112]
## Bug report
Issues trying to import config changes in core store settings in Strapi 4.14.5

### Describe the bug

The config changes can easily get exported, but can't get imported. 

### Steps to reproduce the behavior

Assuming there is an article type. 
for key 'plugin_content_manager_configuration_content_types::api::article.article' 
Running version 4.14.5

1. In local environment do changes requiring changes in the key mentioned above - for example, change a label on a field, make read only, add new field, etc.
2. Export config changes and commit in the repo
3.  Release changes to the hosted environment
4.  In Settings/ConfigSync/Interface page you can see a difference in the config.
5. Click import button
6. You can see the config in diff state and changes are not persisted
3

### Expected behavior

Config changes in core store are imported

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 18.18.1
- NPM version: 9.8.1
- Strapi version: 4.14.5
- Plugin version: 1.1.3
- Database: postgreSQL
- Operating system: debian linux

**Comment by boazpoolman** [comment]
Probably a duplicate of #110

**Comment by boazpoolman** [comment]
Are you sure you're running version 1.1.3 of the plugin?

**Comment by jklimonda** [comment]
Hey,

Yes, been having these issues since yesterday when I updated strapi to 4.14.5. I had the plugin in version 1.1.3. I tried updating the plugin but it didn't help.

**Comment by boazpoolman** [comment]
Hmm. Then it might not be a duplicate of #110.
I'll investigate later.

**Comment by jklimonda** [comment]
Thank you!

**Comment by jklimonda** [comment]
I's lso like to say that other config changes, like admin-role.strapi-author.json go through without issue. I only have an issue with importing changes for the key 'plugin_content_manager_configuration_content_types::api::article.article'

**Comment by boazpoolman** [comment]
Gotcha. That's why I thought it might be related to #110 as that issue also only happens for `plugin_content_manager_configuration_content_types....` config files.

**Comment by boazpoolman** [comment]
@jklimonda Could you run a `yarn why strapi-plugin-config-sync` and paste the output in a comment on this issue.

**Comment by boazpoolman** [comment]
I've made a new release with some fixes ([v1.2.2](https://github.com/boazpoolman/strapi-plugin-config-sync/releases/tag/1.2.2))

Could you install that and see if the issue is resolved?

**Comment by jklimonda** [comment]
Hey. Sorry for late response, today I could test the config changes with the new plugin. It works fine in version 1.2.2

Thank you very much for a rapid fix.

**Comment by nowrap** [comment]
Hello,

I tried the plugin for the first time today. Unfortunately, I have exactly the described problem that the plugin acknowledges the import of core-store.plugin_content_manager_configuration_* positively (GUI and/or shell), but nothing was imported.

I use:
- Strapi v5.12.6
- NodeJS v20.19.1
- NPM v10.8.2
- Plugin v3.1.1
- Ubuntu 24.04.2 LTS

Regards
nowrap

**Comment by nowrap** [comment]
@boazpoolman 
thanks for the reply. I will try. Please give me a moment ;)
