### ISSUE TITLE
Sync admin roles & permissions

### ISSUE THREAD

**Issue by boazpoolman** [boazpoolman/strapi-plugin-config-sync#20]
Similar to how we sync the roles & permissions from the `users-permissions` plugin, I would like for this plugin to be able to sync the admin roles & permissions as well.

**Comment by boazpoolman** [comment]
Released in [v1.0.0-alpha.1](https://github.com/boazpoolman/strapi-plugin-config-sync/releases/tag/1.0.0-alpha.1) for the Strapi v4 version of `strapi-plugin-config-sync`.

**Comment by dominikjasek** [comment]
Wow, thanks. This allows me to use more than 3 strapi roles even on my free tier plan.

**Comment by boazpoolman** [comment]
@dominikjasek Yep 🤫
