### ISSUE TITLE
Managed permissions for access to plugin

### ISSUE THREAD

**Issue by paulpopus** [boazpoolman/strapi-plugin-config-sync#24]
Thanks a lot for your work on this plugin, definitely something Strapi needs as a core feature of the development lifecycle!

I think that there should be managed permissions to access and manage the plugin so that only admins can import (or export) config.

Similar to the Users & Permissions plugin.  
![image](https://user-images.githubusercontent.com/35137243/138666651-613cb415-2264-4361-aeac-cefffea49031.png)

**Comment by boazpoolman** [comment]
Released in [v1.0.0-alpha.1](https://github.com/boazpoolman/strapi-plugin-config-sync/releases/tag/1.0.0-alpha.1) for the Strapi v4 version of `strapi-plugin-config-sync`.
