### ISSUE TITLE
Plugin GUI thinks I'm in production environment

### ISSUE THREAD

**Issue by derrickmehaffy** [boazpoolman/strapi-plugin-config-sync#30]
### Describe the bug

Using the 1.0.0-alpha.1 release is showing an warning (that can't be closed) about being in production while I'm in development 

### Steps to reproduce the behavior

1. Install plugin in fresh v4 project
2. Rebuild Admin
3. Run project with `yarn develop`
4. Navigate to AdminUI for plugin

### Expected behavior

Haven't looked at project code to see where it's pulling the env variable from, but might be pulling from wrong location

### Screenshots

![image](https://user-images.githubusercontent.com/8593673/145303339-0000a5de-da99-417b-b045-f2c5c09c2fd1.png)

![image](https://user-images.githubusercontent.com/8593673/145303391-1b772e1d-24c7-457f-8035-fcc0185e5aa8.png)

### Code snippets

No specific modifications made, just installed and added the cs script to the package.json

### System

- Node.js version: v14.18.1
- NPM version: v6.14.15
- Strapi version: v4.0.0
- Plugin version: v1.0.0-alpha.1
- Database: SQLite
- Operating system: Linux Mint 20.2

### Additional context

Error message doesn't appear it can be closed :P

**Comment by boazpoolman** [comment]
Thanks for the issue submission @derrickmehaffy :)

I fetched the env from `process.env.NODE_ENV`. This gave me the environment of the plugin, where we should grab the environment of Strapi.
I fixed this and will be released with `alpha.2`.

Oh and yeah, I don't want to allow you to click the message away, this is intended.
Though I couldn't find a way to hide the cross when using one of the reusable components from `@strapi/design-system`.
