### ISSUE TITLE
config-sync command not found in CLI

### ISSUE THREAD

**Issue by jkirkpatrick** [boazpoolman/strapi-plugin-config-sync#34]
### Describe the bug

`spawn ENOENT`

CLI does not seem to be installed when installed using Strapi3 (plugin version 0.1.6).

After installation, there is no `config-sync` in `node_modules/.bin` or anywhere in `node_modules/strapi-plugin-config-sync` 

### Steps to reproduce the behavior

1. `npm install --save strapi-plugin-config-sync@0.1.6`
2. Make edits to `config/admin.js` according to README
3. `npm run build`
3. `npm run develop`
4. Stop strapi
5. Make edit to `package.json` (add 'cs' to scripts) according to README
6. `npm run cs`

### Expected behavior

I would expect that 'config-sync' would work from the CLI; I presume a `config-sync` command in the NPM bin search path location (`./node_modules/.bin/`) would be found

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 14.17.6 (LTS)
- NPM version: 6.14.15
- Strapi version: 3.6.8
- Plugin version: 0.1.6
- Database: SQLite3
- Operating system: Linux 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Additional context
I can attach full verbose log file (2022-01-05T19_35_02_110Z-debug.log) if it would help

**Comment by boazpoolman** [comment]
Hey @jkirkpatrick,

As you’ve experienced the config-sync CLI is not available in v0.1.6 of the plugin.

It was introduced in v1.0.0-alpha.1 for Strapi v4.

Please refer to the node_modules/strapi-plugin-config-sync/README.md file in your project for the documentation of the plugin version you’re using.

**Comment by jkirkpatrick** [comment]
Ok, thanks! I'd suggest adding a note to the README indicating that feature is only available with Strapi4.
