### ISSUE TITLE
Plugin is failing when running the CLI command yarn cs export

### ISSUE THREAD

**Issue by mlouage** [boazpoolman/strapi-plugin-config-sync#36]
### Describe the bug

The plugin is failing when running the CLI command yarn cs export. The initial sync through the UI was successful. 

### Steps to reproduce the behavior

1. Open a terminal in the root of the Strapi project
2. Run ```yarn cs export```

### Expected behavior

Expected to have a message that the export was succesful.

### Code snippets

```bash
❯ yarn cs export
yarn run v1.22.17
$ config-sync export
/home/<username>/Play/strapi-postgresql/cms/node_modules/strapi-plugin-config-sync/server/cli.js:163
program.storeOptionsAsProperties(false).allowUnknownOption(true);
        ^

TypeError: program.storeOptionsAsProperties is not a function
    at Object.<anonymous> (/home/<username>/Play/strapi-postgresql/cms/node_modules/strapi-plugin-config-sync/server/cli.js:163:9)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/<username>/Play/strapi-postgresql/cms/node_modules/strapi-plugin-config-sync/bin/config-sync:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### System

- Node.js version: v14 LTS
- NPM version: 6.14.15
- Strapi version: 4.0.3
- Plugin version: 1.0.0-beta.2
- Database: Postgres
- Operating system: Windows 10 in WSL 2 (Ubuntu)
![Screenshot 2022-01-07 120056](https://user-images.githubusercontent.com/844088/148534722-96d4db76-5bea-4f77-8e65-42fae3395c8f.jpg)
![Screenshot 2022-01-07 120210](https://user-images.githubusercontent.com/844088/148534731-7fb80ba6-7de0-4c44-806d-33a7c39c279f.jpg)

**Comment by boazpoolman** [comment]
Thanks for the issue submission! I'll take a look.
For the time being you can just use the GUI to sync your config.
As the issue seems to only be related to the CLI.

**Comment by boazpoolman** [comment]
For my information:
Did you have this working in one of the previous versions?

**Comment by mlouage** [comment]
This is my first time working with Strapi and your plugin. First install. I did however run the default strapi commands
```bash
yarn strapi config:dump --file=dump/config.json
```
and
```bash
yarn strapi config:restore --file=dump/config.json --strategy=replace
``` 

Can that cause something to break? The output directory is different, I chose dump in the root...

**Comment by boazpoolman** [comment]
No that shouldn't cause any issues.
I would however recommend using one or the other. Either this plugin, or the strapi dump/restore commands.
As they do have some overlap.

But thanks for the additional info. I'll get back to you on this.

**Comment by boazpoolman** [comment]
@mlouage I wanna try something out.
I've just released `v1.0.0-beta.3`.
Can you test out if it fixes the issue for you?

**Comment by mlouage** [comment]
Yes that did the trick. Thanks!

![Screenshot 2022-01-07 130012](https://user-images.githubusercontent.com/844088/148541316-e9de13e1-e0ce-46f7-aef2-b9ceebf9b5bb.jpg)

**Comment by mlouage** [comment]
So weird that it works now, you just juggled some dependencies around 😂

**Comment by boazpoolman** [comment]
Yeah, figured I could just remove some dependencies that were inherited from strapi itself.
But I figured wrong. Thanks for testing anyways :)

One step closer to stability :)
