### ISSUE TITLE
cs command not working,  'config-sync' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by fatehMohamed14** [boazpoolman/strapi-plugin-config-sync#45]
## 'config-sync' is not recognized as an internal or external command

plugin works from admin panel but not working from cli, here is my versions

-  "strapi": "3.6.8",
-  "strapi-plugin-config-sync": "0.1.6"

When i try to export config using **npm run cs export** i get this error

`'config-sync' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1`

**Comment by boazpoolman** [comment]
Hi @fatehMohamed14 

Sadly the config-sync CLI was introduced with version `1.0.0-alpha.1` for Strapi v4.
In version `0.1.6` you can only import/export from the Strapi admin GUI.

For documentation of `0.1.6` please refer to:
https://github.com/boazpoolman/strapi-plugin-config-sync/blob/0.1.6/README.md
