### ISSUE TITLE
Config sync no longer shows up in admin panel for Strapi 4.1.5, strapi-plugin-config-sync 1.0.0

### ISSUE THREAD

**Issue by alexdevmotion** [boazpoolman/strapi-plugin-config-sync#48]
### Describe the bug

After upgrading to strapi `4.1.5` and strapi-plugin-config-sync `1.0.0`, Config sync no longer shows up in the admin panel.

### Steps to reproduce the behavior
- update from strapi `4.1.3` and strapi-plugin-config-sync `1.0.0-beta.8` to the versions mentioned above
- build the admin panel: `strapi build`
- start strapi
- config sync no longer shows up in the admin panel 😞

The command line interface still works, though.

### Expected behavior

Config sync still shows up in the Strapi admin panel.

### System

- Node.js version: 16.13.1
- NPM version: 8.3.0
- Strapi version: 4.1.5
- Plugin version: 1.0.0
- Database: sqlite
- Operating system: Windows 11

**Comment by boazpoolman** [comment]
Hey @alexdevmotion,

To have plugin be less invasive, I've moved the admin tool to the **Settings** in your Strapi app.
This plugin is more of a background tooling, so no need to have a dedicated menu item IMO 🙂

**Comment by alexdevmotion** [comment]
Good thinking and thank you for this amazing tool, I find it's really a must have for my Strapi apps.
