### ISSUE TITLE
Support for v3?

### ISSUE THREAD

**Issue by alvitoraidhy** [boazpoolman/strapi-plugin-config-sync#49]
### Summary

Supporting Strapi v3 until it is deprecated.

### Why is it needed?

Considering how young Strapi v4 is and how the migration guide is still in progress, I think it's a good idea to support v3 for now. I'm sure me and other developers are willing to help. It would be great if you can guide us where to start.

### Suggested solution(s)

-

### Related issue(s)/PR(s)

-

**Comment by boazpoolman** [comment]
Hi @alvitoraidhy 

Totally agree with you on this one.
Though I'm gonna say it up front; this is gonna take some effort.
I could for sure help in guiding and facilitating, but we will need more man-power to finish the job in a reasonable time.

From my side a small list of what I think should be done:

**Must haves**
- Copy the CLI from v4 to v3 (should be fairly easy)
- Export the i18n-locales as wel (to fix #8)
- Windows support (#14)

**Nice to haves**
- Partial import/export (#22)
- Sync admin roles/permissions (#20)
- Custom types (#21)

**Comment by boazpoolman** [comment]
I've pushed the latest v3 release of the plugin (0.1.6) to a new branch:
https://github.com/boazpoolman/strapi-plugin-config-sync/tree/v3

You can use that branch to fork and create PR's to.

**Comment by alvitoraidhy** [comment]
Thanks. I'll see what I can contribute

**Comment by boazpoolman** [comment]
Hey @alvitoraidhy 

Did you find some time to work on this?

I wanted to suggest another approach to this; forking the v4 plugin and updating that for v3.
It might take a bit more time but the plugin would be much more feature rich and bug free.

**Comment by alvitoraidhy** [comment]
> Hey @alvitoraidhy
> 
> Did you find some time to work on this?
> 
> I wanted to suggest another approach to this; forking the v4 plugin and updating that for v3. It might take a bit more time but the plugin would be much more feature rich and bug free.

Hi. I haven't found a time to work on this unfortunately. 

Forking the v4 and then updating it all at once could work, but I believe adding the features incrementally is the more appropriate approach for this so if the progress were to stale midway, at least there would be some new features for everyone to use. 

But that's just my thought and I haven't even started working on it anyway.

**Comment by boazpoolman** [comment]
It's been a while and Strapi v3 has since been deprecated.
I'm gonna close this issue, as well as delete the `v3` branch.
This plugin will no longer get updates for v3.
