### ISSUE TITLE
Documentation uses `config-sync` command before adding it

### ISSUE THREAD

**Issue by Helveg** [boazpoolman/strapi-plugin-config-sync#50]
### Describe the bug

When following the README, `npm run config-sync export` is used before instructions appear to add it to `package.json`, and I had this error:

```
PS D:\GIT\hub-cms> npm run config-sync export
npm ERR! Missing script: "config-sync"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
```

It was not available through npm run:

```
PS D:\GIT\hub-cms> npm run
Lifecycle scripts included in XXX:
  start
    strapi start

available via `npm run-script`:
  develop
    strapi develop
  build
    strapi build
  strapi
    strapi
```

### Expected behavior

Be able to follow the README step by step. Instruct the user to add the command (either as `cs` or `config-sync` which should then always be used as such in the rest of the docs)

**Comment by boazpoolman** [comment]
I've just pushed the README change to github.
Thanks for the pointer :)
