### ISSUE TITLE
Return non-zero status when diff is not empty.

### ISSUE THREAD

**Issue by goodhoko** [boazpoolman/strapi-plugin-config-sync#66]
### Summary
Make `config-sync diff` return non-zero status in CLI when the diff is not empty.

### Why is it needed?

I'd like to use `config-sync diff` in my pre-commit git hook to check I didn't forget to export the config before committing (and pushing). Currently, I have to parse the command's output. Returning non-zero status when the diff is not empty would make this easier and also would bring the command's API in line with the [POSIX](https://pubs.opengroup.org/onlinepubs/009696799/utilities/diff.html) diff and diff commands on most systems.

### Suggested solution(s)

Just make the return value conditional on the diff contents. Alternatively, provide a `--check` option to enable this behaviour.

### Related issue(s)/PR(s)

Didn't find any.

---

I'll be happy to submit a PR if you agree with this proposal. Oh and thanks for all you work on this plugin! 🖤

**Comment by boazpoolman** [comment]
Hi @goodhoko,

Thanks for the feature request.

Can we let the CLI return a non-zero status and keep the output the same as it currently is?

It would be great if you could put up a PR ❤️

**Comment by goodhoko** [comment]
> Can we let the CLI return a non-zero status and keep the output the same as it currently is?

Definitely, these are independent.

> It would be great if you could put up a PR ❤️

Sure. Will post one soon.
