### ISSUE TITLE
"importOnBootstrap: false" is being ignored

### ISSUE THREAD

**Issue by idesignpixels** [boazpoolman/strapi-plugin-config-sync#72]
## Bug report

When deploying to our staging environment the config seems to automatically update our database rather than a manual sync through the admin panel GUI.

After looking at the docs we saw `importOnBootstrap` and that is was set to `false` by default, we ran a test with the config override in config/plugins.ts also set to `false` and created some dummy content to see if it auto populated the database which it did.

We are using version 1.0.4

### Expected behaviour

That `importOnBootstrap` being set to `false` stops any auto population.

### Code snippets

```json
'config-sync': {
    enabled: true,
    config: {
      syncDir: "config/sync/",
      minify: false,
      importOnBootstrap: false,
      customTypes: [],
      excludedTypes: [],
      excludedConfig: [
        "core-store.plugin_users-permissions_grant"
      ],
    },
  },
```

### System

- Node.js version: 16
- NPM version: 8.15.0
- Strapi version: 4.3.6
- Plugin version:  1.0.4
- Database: postgres

**Comment by boazpoolman** [comment]
Hi @idesignpixels,

That is very odd. I’m pretty sure the importonbootstrap functionality only works when the setting is actually set to true.

You are talking about auto population. Could you describe in detail the things that are imported automatically? Is it permissions, or something else? Also maby a video of the issue happening could help me diagnose the problem a bit better as wel.

**Comment by idesignpixels** [comment]
Hi @boazpoolman,

Our process is

> local
Make changes/create content types.
go to config sync settings
export
new file/s/changes appear for version control
commit & push changes
> CI
push triggers a new docker image deployment
a new container is created where the latest deployed Strapi codebase is started
once complete traffic is directed to the new container & the old container is removed, the DB is consistent between them.

We expected that when staging was deployed that we'd go into the config sync settings and the import button would be active along with diff for us to manually implement but there's no diff and the database already has the config from the change.

I have asked our dev ops engineer if there were any logs that might indicate this happening but nothing can be seen but we have confirmed this with a test by adding a dummy content type and seeing the config in the database after it's deployed.
We're just concerned that the plugin appears to be automatically syncing changes without us being able to review.

**Comment by idesignpixels** [comment]
Could `importAllConfig` be running automatically somewhere else?

**Comment by boazpoolman** [comment]
So, the only place the importing on bootstrap _can_ happen is in the bootstrap function.
And in there the importing only happens when the setting is actually set to `true`. [See the code](https://github.com/boazpoolman/strapi-plugin-config-sync/blob/master/server/bootstrap.js#L49).

> We expected that when staging was deployed that we'd go into the config sync settings and the import button would be active along with diff for us to manually implement but there's no diff and the database already has the config from the change.
Yes. This is exactly how it works.

Though I'm still wondering what config is imported automatically on your side.
Because content types are managed by Strapi's `schema.json` files, which will migrate automatically during bootstrap.
So when you create a dummy content type and deploy the code, Strapi will create the tables for the content type on bootstrap. That's a seperate thing from this plugin.
What this plugin will do is create config files for all the things that Strapi doesn't natively migrate them selfs.
That is things like permissions, plugin settings and i18n locales.

**Comment by idesignpixels** [comment]
@boazpoolman thanks, it might be our misunderstanding, the only files in src for that commit were:

`src/components/do-not-use/dummy-test.json`
`config/sync/core-store.plugin_content_manager_configuration_components##do-not-use.dummy-test.json`

Are you saying strapi is creating the new tables from it's own json config files? (the first file)?

**Comment by boazpoolman** [comment]
> Are you saying strapi is creating the new tables from it's own json config files? (the first file)?

Yes exactly.

**Comment by boazpoolman** [comment]
I'm gonna be closing this issue as it was a misunderstanding about the functionality of the plugin.
If you have any more questions about this topic feel free to re-open the issue or create another one.
