### ISSUE TITLE
Add 'soft' setting to importOnBootstrap to prevent overwriting of existing changes in DB

### ISSUE THREAD

**Issue by BabyDino** [boazpoolman/strapi-plugin-config-sync#74]
_Originally posted by @BabyDino in https://github.com/boazpoolman/strapi-plugin-config-sync/issues/68#issuecomment-1277519222_

When we roll out an API we would love to use the `importOnBootstrap` setting, but we want to prevent existing changed data of being reimported.

One example:
- We have a table with e-mail templates. In our dev, we export staging/production ready email templates.
- We'd like to use `importOnBootstrap` on staging/production, which would be ideal for a first run.
- Now we change an imported template in staging or production
- On the next run, `importOnBootstrap` overrides the customized template with the dev template.

So basically, if the state is `Different` for a template, we would like to have that entry skipped by `importOnBootstrap`. We only like to import the state `Only in sync dir` with `importOnBootstrap`.

**Comment by boazpoolman** [comment]
Thanks for creating the seperate issue 🙂

**Comment by boazpoolman** [comment]
Hi @BabyDino,

I've put up a PR implementing my take on solving the problem you posted.
I've written some instructions in the PR description on how to test the new feature.
Could you test this out in your env and see if it works correctly. :)

**Comment by BabyDino** [comment]
Thank you for the PR, we will take a look!
