### ISSUE TITLE
Add ability to track webhooks

### ISSUE THREAD

**Issue by DenisBalan** [boazpoolman/strapi-plugin-config-sync#76]
## Feature request
Add ability to track webhooks

### Summary

Track webhooks as config as well, so that when deploying/migrating from env to env we have this tracked, and not create manually for each env.

### Why is it needed?

devops style in mind.

### Suggested solution(s)

Should be pretty easy as we track almost all other changes.

**Comment by boazpoolman** [comment]
Hi @DenisBalan,
Thank you for submitting this issue.

As of now, I won’t register webhooks as a default config type. Though it is still possible for you to track them by using custom config types. There is even an example in the documentation for webhooks you can copy-paste. Please see [the documentation](https://github.com/boazpoolman/strapi-plugin-config-sync#custom-types).

**Comment by boazpoolman** [comment]
Hi @DenisBalan,

Hope you managed to make it work based on my instructions. I'm gonna close the issue as this will not be worked on.

If you still have questions feel free to re-open te issue.
