### ISSUE TITLE
Discriminate sections by status aka show only different files(from db) in import and vis.

### ISSUE THREAD

**Issue by SalahAdDin** [boazpoolman/strapi-plugin-config-sync#79]
### Summary
It would be nice if the plugin shows only files with differences with the database in the import view and files with differences with existing files in the export files.

### Why is it needed?

I saw a big problem when coming to Media Library settings many times after importing all my configurations; later I realized that I was importing even the settings from the database, duplicating and corrupting, I think, the database.

It was not clear to me that importing settings from the database itself could corrupt the database, and I think it could be a general problem for many users.

### Suggested solution(s)

Like a tab with import showing only the files that have differences with the database, and an export tab showing only the files that either is not in the configuration folder or have differences with the files in the folder.

### Related issue(s)/PR(s)
I think I made this suggestion before, but I'm not pretty sure.

**Comment by boazpoolman** [comment]
Hi @SalahAdDin,

If I understand correctly you do the following:
1. Import config on a remote env (like staging)
2. Change media library setting in the gui on the staging env
3. Then make a new release and import again
4. The changes you made in 2 are gone.

This is how the plugin is intended to work. It is an all or nothing approach. Once you use this plugin you are forced into this workflow. If you want to make a change to media library settings you have to make that change locally, export the config, push to git, pull on the remote env and import it. You cannot carelessly change configuration on remote envs as it will be overwritten next deploy.

I’m currently working on a feature to implement a new setting that will help you import more gracefully and prevent losing data by importing. See PR #78 if you’re interested.

**Comment by SalahAdDin** [comment]
No,

What we want is a tab for import and a tab for export, so we would not import data directly from the database itself in anycase.

**Comment by boazpoolman** [comment]
I’m still not quite on your page here.
A different tab for import and export would just show the same changes. The difference is in the action you do: import or export.

Also: you would never import _from_ the database. Importing write the data from the files _to_ the db.

Could you help me understand your problem a bit more?

**Comment by SalahAdDin** [comment]
> I’m still not quite on your page here. A different tab for import and export would just show the same changes. The difference is in the action you do: import or export.
> 
> Also: you would never import _from_ the database. Importing write the data from the files _to_ the db.
> 
> Could you help me understand your problem a bit more?

Yeah, that's the problem: if you do not know importing from the database is dangerous, you won't care about what you are importing, you just do import without worrying about the selected files.

But, if you separate files
 in views, even if you don't care what you are importing, you won't have conflicts and importing.

But as far as I can remember, we argued about this before.

**Comment by boazpoolman** [comment]
Allright. I think I understand your proposal. Though it is not something that is in line with my vision for this plugin. Sorry.

This plugin is a dangerous tool. That is also what makes it powerful. I’m sure you’re not the first to have accidentally imported something they shouldn’t have and you’re certainly not gonna be the last. It’s just something you have to get used to once your start using this plugin.

**Comment by boazpoolman** [comment]
I'm gonna be closing this issue as it won't be worked on.
