### ISSUE TITLE
Docker usage | Segmentation fault inside container

### ISSUE THREAD

**Issue by rortan134** [boazpoolman/strapi-plugin-config-sync#82]
## Bug report

Using the official strapi [docker compose container](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/installation/docker.html#development-and-or-staging-environments), Using the latest strapi version (^4.5.6) I tried setting up the config sync plugin running export just before `yarn start` and I'm getting a segmentation fault code 139

```
/*
* Dockerfile
*/
// ...rest of the dockerfile
COPY --from=build /opt/node_modules ./node_modules
ENV PATH /opt/node_modules/.bin:$PATH
COPY --from=build /opt/app ./

EXPOSE ${STRAPI_PORT}

RUN yarn cs export -y // <--

CMD ["yarn", "start"]
```

Tried doing a clean install, deleting node_modules, deleting all docker caches and still nothing

### Steps to reproduce the behavior

1. Go to https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/installation/docker.html#development-and-or-staging-environments
2. Copy dockerfile & docker-compose.yml to a regular strapi app
3. Add cs export and run docker compose build

### Expected behavior

Config gets exported to docker image and can safely migrate environments

### Screenshots

![image](https://user-images.githubusercontent.com/37253958/212220394-7646b10f-9819-463c-adda-d0ce1d265036.png)

### System

- Node.js version: 16.18.0
- YARN version: 1.22.19
- Strapi version: ^4.5.6
- Plugin version: ^1.10
- Database: sqlite
- Operating system: Windows (WSL2)

**Comment by boazpoolman** [comment]
I'm gonna have to do some testing with this. Thanks for reporting.

**Comment by boazpoolman** [comment]
One thing that caught my attention was the `Segmentation fault` log.
That would indicate a memory access fault. Which could be caused because the plugin is trying to write to a read-only location.

I don't use docker in this way myself so I can't confirm, but I've heard of docker containers being read-only.

**Comment by boazpoolman** [comment]
By courtesy of @eventyret I would like to ask you to try and use the [dockerize tool](https://github.com/strapi-community/strapi-tool-dockerize) from the community org and setup docker with that. Let's see if the issue still persists after that.

**Comment by Eventyret** [comment]
Did you find anything @rortan134 😸

**Comment by boazpoolman** [comment]
I'm gonna close this due to inactivity
