### ISSUE TITLE
Can i seed a content-type like config default ?

### ISSUE THREAD

**Issue by haidv1992** [boazpoolman/strapi-plugin-config-sync#85]
### Summary

Quick summary what's this feature request about.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request.

**Comment by boazpoolman** [comment]
Could you elaborate more on this?
You seem to have forgotten to write a description.

**Comment by haidv1992** [comment]
thank for your reply
 I mean  when  create a content-type like config , so I can backup all record in this content-type and seeder when deploy

**Comment by boazpoolman** [comment]
I still don’t quite understand.
Do you want to seed the db with data from your custom content type? You can do that by registering custom types. See docs; https://github.com/boazpoolman/strapi-plugin-config-sync#custom-types

**Comment by boazpoolman** [comment]
Hi @haidv1992,

Have you managed to make it work using the custom config types?

**Comment by boazpoolman** [comment]
I'm gonna close this due to inactivity.
