### ISSUE TITLE
Admins gives errors at first export

### ISSUE THREAD

**Issue by SalahAdDin** [boazpoolman/strapi-plugin-config-sync#9]
We are testing this plugin in order to import our development settings.

At the first use, we exported the configuration but it gave us an error message and it was not refreshed, the problem here is, ever document was exported properly:
![image](https://user-images.githubusercontent.com/5034215/119223414-fda8ed80-bb01-11eb-84e2-5e62c2bca1df.png)

After refreshing it we got the changed files, whitout any problem.

What's the bug here?

**Comment by boazpoolman** [comment]
Hi @SalahAdDin,
Thanks for your issue submission.

I think this issue can be prevented by adding the sync dir to the watchIgnore files setting in Strapi.
This way your app will not restart upon config file changes, which is the desired outcome.

You can do this by editing the `config/server.js` file in your strapi project and adding the following:
```
admin: {
  auth: {
 	// ...
  },
  watchIgnoreFiles: [
    '**/config-sync/files/**',
  ],
},
```

Please let me know if this fixes the issue! :)

**Comment by SalahAdDin** [comment]
@boazpoolman That's why we reported it: `watchIgnoreFiles: ["**/config-sync/files/**"],` is already on our settings.
