### ISSUE TITLE
Does not export data

### ISSUE THREAD

**Issue by hassanzadeh** [boazpoolman/strapi-plugin-config-sync#90]
Hey Guys,
I don't know if this is a bug or the feature is not implemented, but on the market it says: "This plugin is a multi-purpose tool to manage your Strapi database records through JSON files", but the database records are not exported actually. Is this plugin useful for exporting the entries as well? When I add a new record and I Retrigger an export, it says: [notice] There are no changes to export.

THanks

**Comment by boazpoolman** [comment]
It really depends on what kind of records you are creating. By default just 4 types will be tracked. Please read the [config types](https://github.com/boazpoolman/strapi-plugin-config-sync#-config-types) section of the readme. If you want to track other type of records you can register them through the customTypes plugin config. Also documented in the readme.

**Comment by hassanzadeh** [comment]
I'm using just very regular content types, say the default User type, and create a single user. Even that is not exported.

**Comment by hassanzadeh** [comment]
Ok, maybe we are talking about different things, I'm talking about records not types, for example the default boilerplate comes with a User type, when you create an specific user (eg, user John Doe, with relevant fields), those types of data are not exported.

**Comment by boazpoolman** [comment]
I think you might misunderstand the use of this plugin. I would like to redirect you to [this article](https://strapi.io/blog/strapi-marketplace-plugin-highlight-config-sync) to get some more insight.

Quoting from the article:

> This plugin is not for all your database records. It is really meant for those config tables of which the records are mainly created/updated by the developer, not by the client. You are free to use this plugin for any table you want, but by default, 4 tables are tracked.

If you are looking for a full-on database dump, exporting everything without continuous graceful imports you might be better of using the [native data management system](https://docs.strapi.io/dev-docs/data-management).

**Comment by hassanzadeh** [comment]
Got it, thanks for that.
