### ISSUE TITLE
Ignore environment specific api upload folder

### ISSUE THREAD

**Issue by n2o** [boazpoolman/strapi-plugin-config-sync#92]
The config-sync plugin in version 1.1.2 tries to sync the id of the api folder over different environment, which does not make any sense. We discussed it in [this forum post](https://forum.strapi.io/t/strapi-v4-10-1-generates-multiple-api-upload-directories/28050/3?u=n2o).

So add the configuration option or wait for the next release :-) 

```
excludedConfig: ["core-store.plugin_upload_api-folder"],
```

Documenting this for people having the same issue.

**Comment by boazpoolman** [comment]
This has been fixed and released with `v1.1.3`
