### ISSUE TITLE
Config changes for admin-role.strapi-super-admin cant be overwritten

### ISSUE THREAD

**Issue by bart-iimpcoll** [boazpoolman/strapi-plugin-config-sync#98]
### Describe the bug

Hello! I've been using this plugin for a while and it's great! I ran so far only into one issue with 'Config changes for admin-role.strapi-super-admin'. I have settings in my database that can't be overwritten even with --force. 

![Screenshot 2023-08-22 at 14 57 14](https://github.com/boazpoolman/strapi-plugin-config-sync/assets/129974513/df648daa-c485-4768-a036-4452b4a8b9bf)

Do you have any suggestion what to do about it? 

### System

- Node.js version: v18 LTS
- NPM version: 
- Strapi version:     "@strapi/strapi": "4.11.1",
- Plugin version:     "strapi-plugin-config-sync": "^1.1.2",
- Database: postgres
- Operating system: MacOS/Linux

**Comment by boazpoolman** [comment]
Hi @bart-iimpcoll,

It seems like your Strapi instance has multiple admin permissions with the same `action` key. That is a case this plugin does not handle, as these duplicate permissions are essentially useless. Just one of each will suffice.

I guess my question would be, how did you get here? I don't see how the plugin could've accidentally created those duplicate permissions.

**Comment by bart-iimpcoll** [comment]
Thank you for your answer. That is a great question. I honestly don't know. I checked my git history and it seems I deleted the file and then in the next commit it appeared with duplicates. 

Is there any way of hard resetting this?

**Comment by boazpoolman** [comment]
You could truncate your admin permissions table and afterwards run a config import. I think that will resolve this issue for you.

Make sure to backup the table before you truncate so you can restore if needed.

**Comment by bart-iimpcoll** [comment]
Thank you for your help. I tried different approaches and in the end manually removed the duplicated rows from DB and then resynced all and now it works
