### ISSUE TITLE
Admin GUI doesn't show up with Strapi v4.12.5

### ISSUE THREAD

**Issue by karlkeefer** [boazpoolman/strapi-plugin-config-sync#99]
### Describe the bug

Installing `config-sync` on a relatively clean Strapi install doesn't show the Admin GUI in the sidebar, even though the CLI tools work as expected, and the plugin _is_ listed from the plugins page. I'm new to using Strapi - apologies if I'm missing an obvious step!

![screenshot](https://github.com/boazpoolman/strapi-plugin-config-sync/assets/305272/95e03d16-2040-417f-aa85-7ddfbdac2d9c)

**Comment by boazpoolman** [comment]
Hi @karlkeefer,

This plugin does not render a top level menu item like the media library does. It rather renders a section within the setting. Like the users permissions plugin does as well.

You should be able to find the admin page under the settings tab in you Strapi instance.

**Comment by karlkeefer** [comment]
Ah - thank you for pointing me in the right direction.

The image of the admin GUI is out of date, then - it shows something in the sidebar behind the modal.
<img width="1103" alt="config-diff" src="https://github.com/boazpoolman/strapi-plugin-config-sync/assets/305272/2aaa7028-b681-4d3f-ba5b-4409793a2aae">

I made an updated screenshot. PR incoming!
